name: cash_register_app
description: تطبيق Flutter لإدارة صندوق المتجر مع دعم العربية.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.0
  go_router: ^13.0.0
  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.20
  path: ^1.8.3
  path_provider: ^2.1.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.18.1
  data_table_2: ^2.5.6
  fl_chart: ^0.66.2
  crypto: ^3.0.3
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  drift_dev: ^2.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/
